version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

  mimir:
    image: grafana/mimir:latest
    command: ["mimir", "--config.file=/etc/mimir/config.yaml"]
    volumes:
      - ./config/mimir/config.yaml:/etc/mimir/config.yaml
    ports:
      - "9009:9009"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  turing:
    image: turing:latest
    ports:
      - "7777:7777"
