version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

  turing:
    image: turing:latest
    ports:
      - "7777:7777"
