global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: turing
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - turing:7777
